### ISSUE TITLE
Missing  wget

### ISSUE THREAD

**Issue by stappersg** [CumulusNetworks/DUE#12]
Please add   `wget` to the default installed programs.

**Comment by stappersg** [comment]
A patch
[0001-Install-wget.patch.txt](https://github.com/CumulusNetworks/DUE/files/4914996/0001-Install-wget.patch.txt)

**Comment by ehdoyle** [comment]
I'll add this in the pre-install-config.sh script under common-templates/  after the templates get merged in, this is part of the first configuration to run, and will be there by default unless a template overrides it with it's own pre-install-config.sh script.
At which point the creator of the template gets to own the issue :)
