### ISSUE TITLE
Error when due create on a debian 10 VM

### ISSUE THREAD

**Issue by sramkrishna** [CumulusNetworks/DUE#31]
Hi folks,
I'm attempting to build an ONIE image using DUE - I don't have an installed debian system so I decided to go with a VM running Debian 10 and then running docker that way. However when I execute the due create command I get the following:

sri@debian:~/src/DUE$ ./due --create --from debian:9  --description "ONIE Build Debian 9" --name onie-build-debian-9 --prompt ONIE-9 --tag onie --use-template onie
==== Setting --use-template path to /home/sri/src/DUE/templates/onie    ====

 __________________________________________________________________________ 
|
| Creating work directory /home/sri/src/DUE/due-build-merge
|__________________________________________________________________________ 

 __________________________________________________________________________ 
|
| Copying /home/sri/src/DUE/templates/common-templates to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
|__________________________________________________________________________ 

==== Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ====
      total 36
      -rw-r--r-- 1 sri sri  554 Jan 21 10:29 Dockerfile.config
      -rw-r--r-- 1 sri sri 1904 Jan 21 10:29 Dockerfile.template
      -rw-r--r-- 1 sri sri 3453 Jan 21 10:29 duebuild-readme.md
      drwxr-xr-x 4 sri sri 4096 Jan 21 10:29 filesystem
      -rw-r--r-- 1 sri sri 5267 Jan 21 10:29 install-config-common-lib.template
      -rwxr-xr-x 1 sri sri  589 Jan 21 10:29 post-install-config.sh.template
      -rwxr-xr-x 1 sri sri 2479 Jan 21 10:29 pre-install-config.sh.template
      -rw-r--r-- 1 sri sri 1215 Jan 21 10:29 README.md

 __________________________________________________________________________ 
|
| Merging in [ onie-build-debian-9 ] specific files from /home/sri/src/DUE/templates/onie to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
|__________________________________________________________________________ 

==== Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ====
      total 48
      -rw-r--r-- 1 sri sri  656 Jan 21 10:29 Dockerfile.config
      -rw-r--r-- 1 sri sri 1904 Jan 21 10:29 Dockerfile.template
      -rw-r--r-- 1 sri sri 3453 Jan 21 10:29 duebuild-readme.md
      drwxr-xr-x 4 sri sri 4096 Jan 21 10:29 filesystem
      -rw-r--r-- 1 sri sri 5267 Jan 21 10:29 install-config-common-lib.template
      -rwxr-xr-x 1 sri sri 7882 Jan 21 10:29 post-install-config.sh.template
      -rwxr-xr-x 1 sri sri 2479 Jan 21 10:29 pre-install-config.sh.template
      -rw-r--r-- 1 sri sri 8722 Jan 21 10:29 README.md

 __________________________________________________________________________ 
|
| Creating directory to be used for container build at: [ onie-build-debian-9 ]
|__________________________________________________________________________ 

==== Copying non-template files from [ /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ] to [ onie-build-debian-9 ] ====
sending incremental file list
created directory /home/sri/src/DUE/due-build-merge/onie-build-debian-9
./
Dockerfile.config
README.md
duebuild-readme.md
filesystem/
filesystem/etc/
filesystem/etc/apt/
filesystem/etc/apt/sources.list.d/
filesystem/etc/apt/sources.list.d/stretch-backports.list
filesystem/usr/
filesystem/usr/local/
filesystem/usr/local/bin/
filesystem/usr/local/bin/container-create-user.sh
filesystem/usr/local/bin/duebuild

sent 42,201 bytes  received 245 bytes  84,892.00 bytes/sec
total size is 41,476  speedup is 0.98
==== Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9 ====
      total 24
      -rw-r--r-- 1 sri sri  656 Jan 21 10:29 Dockerfile.config
      -rw-r--r-- 1 sri sri 3453 Jan 21 10:29 duebuild-readme.md
      drwxr-xr-x 4 sri sri 4096 Jan 21 10:29 filesystem
      -rw-r--r-- 1 sri sri 8722 Jan 21 10:29 README.md

ERROR at libdue line 1331 :  Cannot map [ i686 ] to a Docker contianer type. Exiting.

---

I don't know if this is because I'm not running Debian on bare metal or what. I'm running this under GNOME Boxes - which is a libvirt based VM technology running on Fedora Silverblue 33.

**Comment by sramkrishna** [comment]
Here it is again with a bash -x log. The problem seems to be that uname -m returns i686 instead of x86_64  - this could be because of how the VM was built.
sri@debian:~/src/DUE$ bash -x due --create --from debian:9  --description "ONIE Build Debian 9" --name onie-build-debian-9 --prompt ONIE-9 --tag onie --use-template onie
+ INSTALLED_DUE_DIR=/usr/share/due
+ LIBRARY_FILE=/usr/lib/libdue
+ '[' -e ./libdue ']'
++ pwd
+ TOP_LEVEL_DIR=/home/sri/src/DUE
+ LIBRARY_FILE=/home/sri/src/DUE/libdue
+ '[' '!' -e /home/sri/src/DUE/libdue ']'
+ . /home/sri/src/DUE/libdue
++ shopt -s extglob
++ DUE_VERSION=2.3.0
++ REQUIRED_PACKAGES=' docker.io rsync bsdutils git'
++ RECOMMENDED_PACKAGES=' binfmt-support qemu qemu-user-static '
+++ whoami
++ USER_NAME=sri
+++ id -u
++ USER_ID=1000
+++ id -g
++ USER_GROUP_ID=1000
+++ getent group 1000
+++ cut -d: -f1
++ USER_GROUP_NAME=sri
+++ realpath /home/sri/
++ HOST_HOME_DIR=/home/sri
++ LOGIN_SHELL='/bin/bash --login'
++ FILTER_SHOW_ONLY_DUE=TRUE
++ DOCKER_IMAGE_TAG=latest
++ KNOWN_IMAGES='
 debian:10
 ubuntu:18.04
 arm32v5/debian:jessie
 arm32v7/debian:10
 arm64v8/debian:10
 ppc64le/debian:10
'
++ DUE_USER_CONTAINER_LIMIT=10
++ SPECIFIC_TEMPLATES_DIR=templates
++ COMMON_TEMPLATE_DIR=templates/common-templates
++ SYSTEM_TEMPLATE_INSTALL_DIR=/usr/share/due
++ '[' /home/sri/src/DUE = '' ']'
++ TEMPLATE_INSTALL_PATH=/home/sri/src/DUE
++ COMMON_TEMPLATE_PATH=/home/sri/src/DUE/templates/common-templates
++ SPECIFIC_TEMPLATE_PATH=/home/sri/src/DUE/templates
++ USE_TEMPLATE_PATH=/home/sri/src/DUE/templates/common-templates
++ DUE_IMAGE_TYPE_LABEL=default-type
+++ pwd
++ BUILD_MERGE_DIR=/home/sri/src/DUE/due-build-merge
++ '[' -e /etc/redhat-release ']'
++ OS_TYPE=Debian
++ PACKAGE_UPDATE=' apt-get update '
++ PACKAGE_INSTALL=' apt-get install '
++ DELETE_SCRIPT=delete_these_docker_images.sh
++ SELECTED_CONTAINER_ID=
++ SELECTED_CONTAINER_NAME=
++ DUE_CONFIG_FILE_PATH=/etc/due/due.conf
++ DUE_HOME_CONFIG_DIR=/home/sri/.config/due
++ DUE_HOME_CONFIG_FILENAME=due.conf
++ DUE_HOME_CONFIG_ABSOLUTE_PATH=/home/sri/.config/due/due.conf
++ CONFIG_FILE_PATH=/home/sri/.config/due/due.conf
++ STOP_SCRIPT=stop_these_docker_containers.sh
+ VERBOSITY_LEVEL=0
++ basename due
+ DUE_NAME=due
+ fxnReadConfigFile
+ local configVars
+ local homeDir
+ local maxContainers
+ '[' '!' -e /home/sri/.config/due/due.conf ']'
+ '[' -e /home/sri/.config/due/due.conf ']'
++ grep -v '#' /home/sri/.config/due/due.conf
++ grep '\S'
+ configVars=DUE_USER_CONTAINER_LIMIT=10
++ echo DUE_USER_CONTAINER_LIMIT=10
++ grep DUE_ENV_DEFAULT_HOMEDIR
++ tail -n 1
+ homeDir=
+ '[' '' '!=' '' ']'
++ echo DUE_USER_CONTAINER_LIMIT=10
++ grep DUE_USER_CONTAINER_LIMIT
++ tail -n 1
+ maxContainers=DUE_USER_CONTAINER_LIMIT=10
+ '[' DUE_USER_CONTAINER_LIMIT=10 '!=' '' ']'
+ DUE_USER_CONTAINER_LIMIT=10
+ DO_CREATE_IMAGE_NOW=TRUE
+ '[' --create = '' ']'
+ [[ 13 -gt 0 ]]
+ term=--create
+ case $term in
+ fxnParseCreateArgs --create --from debian:9 --description 'ONIE Build Debian 9' --name onie-build-debian-9 --prompt ONIE-9 --tag onie --use-template onie
+ [[ 13 -gt 0 ]]
+ term=--create
+ case $term in
+ '[' --from = '' ']'
+ shift
+ [[ 12 -gt 0 ]]
+ term=--from
+ case $term in
+ '[' debian:9 = '' ']'
+ FROM_IMAGE_TYPE=debian:9
+ '[' '' = '' ']'
+ IMAGE_DESCRIPTION='debian:9 Image'
+ DO_CREATE_DIRECTORY=TRUE
+ shift
+ shift
+ [[ 10 -gt 0 ]]
+ term=--description
+ case $term in
+ IMAGE_DESCRIPTION='ONIE Build Debian 9'
+ shift
+ shift
+ [[ 8 -gt 0 ]]
+ term=--name
+ case $term in
+ NEW_IMAGE_NAME=onie-build-debian-9
+ [[ onie-build-debian-9 =~ [A-Z] ]]
+ shift
+ shift
+ [[ 6 -gt 0 ]]
+ term=--prompt
+ case $term in
+ NEW_PROMPT=ONIE-9
+ shift
+ shift
+ [[ 4 -gt 0 ]]
+ term=--tag
+ case $term in
+ DOCKER_IMAGE_TAG=onie
+ [[ onie =~ [A-Z] ]]
+ shift
+ shift
+ [[ 2 -gt 0 ]]
+ term=--use-template
+ case $term in
+ '[' onie = '' ']'
+ MERGE_IN_TEMPLATE_PATH=onie
+ '[' '!' -e onie ']'
+ '[' -e /home/sri/src/DUE/templates/onie ']'
+ MERGE_IN_TEMPLATE_PATH=/home/sri/src/DUE/templates/onie
+ fxnPP 'Setting --use-template path to /home/sri/src/DUE/templates/onie'
+ printf '==== %-66s ====\n' 'Setting --use-template path to /home/sri/src/DUE/templates/onie'
==== Setting --use-template path to /home/sri/src/DUE/templates/onie    ====
+ shift
+ shift
+ [[ 0 -gt 0 ]]
+ '[' '' = TRUE ']'
+ '[' '' = TRUE ']'
+ break
+ '[' '' = TRUE ']'
+ grep -q docker
+ groups
+ '[' 0 '!=' 0 ']'
+ '[' '' = TRUE ']'
+ '[' '' '!=' '' ']'
+ '[' 0 -ne 0 ']'
+ '[' '' = TRUE ']'
+ '[' '' = TRUE ']'
+ '[' TRUE = TRUE ']'
+ '[' debian:9 = '' ']'
+ '[' onie-build-debian-9 = '' ']'
+ fxnMakeNewDockerImage debian:9 onie-build-debian-9
+ local imageFrom=debian:9
+ local imageName=onie-build-debian-9
+ '[' onie-build-debian-9 = '' ']'
+ '[' debian:9 = '' ']'
+ CONFIGURED_NAME_AND_TAG=due-onie-build-debian-9:onie
++ which docker
+ '[' /usr/bin/docker = '' ']'
+ '[' '!' -e /home/sri/src/DUE/due-build-merge/onie-build-debian-9 ']'
+ '[' /home/sri/src/DUE/templates/onie '!=' '' ']'
+ fxnGenerateTemplate /home/sri/src/DUE/templates/onie
+ local name
+ local templateName
+ name=onie-build-debian-9
+ templateName=onie-build-debian-9-template-merge
+ '[' '!' -d /home/sri/src/DUE/due-build-merge ']'
+ fxnHeader 'Creating work directory /home/sri/src/DUE/due-build-merge'
+ echo ''

+ echo ' __________________________________________________________________________ '
 __________________________________________________________________________ 
+ echo '|'
|
+ echo '| Creating work directory /home/sri/src/DUE/due-build-merge'
| Creating work directory /home/sri/src/DUE/due-build-merge
+ echo '|__________________________________________________________________________ '
|__________________________________________________________________________ 
+ echo ''

+ fxnEC mkdir -p /home/sri/src/DUE/due-build-merge
+ mkdir -p /home/sri/src/DUE/due-build-merge
+ status=0
+ '[' 0 -ne 0 ']'
+ return 0
+ '[' -e /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ']'
+ fxnHeader 'Copying /home/sri/src/DUE/templates/common-templates to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
+ echo ''

+ echo ' __________________________________________________________________________ '
 __________________________________________________________________________ 
+ echo '|'
|
+ echo '| Copying /home/sri/src/DUE/templates/common-templates to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
| Copying /home/sri/src/DUE/templates/common-templates to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ echo '|__________________________________________________________________________ '
|__________________________________________________________________________ 
+ echo ''

+ fxnEC cp --recursive --preserve /home/sri/src/DUE/templates/common-templates /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ cp --recursive --preserve /home/sri/src/DUE/templates/common-templates /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ status=0
+ '[' 0 -ne 0 ']'
+ return 0
+ fxnListDirContents /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ fxnPP 'Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
+ printf '==== %-66s ====\n' 'Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
==== Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ====
+ ls -l /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ sed -e 's/^/      /g'
      total 36
      -rw-r--r-- 1 sri sri  554 Jan 21 10:29 Dockerfile.config
      -rw-r--r-- 1 sri sri 1904 Jan 21 10:29 Dockerfile.template
      -rw-r--r-- 1 sri sri 3453 Jan 21 10:29 duebuild-readme.md
      drwxr-xr-x 4 sri sri 4096 Jan 21 10:29 filesystem
      -rw-r--r-- 1 sri sri 5267 Jan 21 10:29 install-config-common-lib.template
      -rwxr-xr-x 1 sri sri  589 Jan 21 10:29 post-install-config.sh.template
      -rwxr-xr-x 1 sri sri 2479 Jan 21 10:29 pre-install-config.sh.template
      -rw-r--r-- 1 sri sri 1215 Jan 21 10:29 README.md
+ fxnHeader 'Merging in [ onie-build-debian-9 ] specific files from /home/sri/src/DUE/templates/onie to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
+ echo ''

+ echo ' __________________________________________________________________________ '
 __________________________________________________________________________ 
+ echo '|'
|
+ echo '| Merging in [ onie-build-debian-9 ] specific files from /home/sri/src/DUE/templates/onie to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
| Merging in [ onie-build-debian-9 ] specific files from /home/sri/src/DUE/templates/onie to /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ echo '|__________________________________________________________________________ '
|__________________________________________________________________________ 
+ echo ''

+ fxnEC cp --dereference --recursive --preserve /home/sri/src/DUE/templates/onie/Dockerfile.config /home/sri/src/DUE/templates/onie/filesystem /home/sri/src/DUE/templates/onie/post-install-config.sh.template /home/sri/src/DUE/templates/onie/README.md /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge/
+ cp --dereference --recursive --preserve /home/sri/src/DUE/templates/onie/Dockerfile.config /home/sri/src/DUE/templates/onie/filesystem /home/sri/src/DUE/templates/onie/post-install-config.sh.template /home/sri/src/DUE/templates/onie/README.md /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge/
+ status=0
+ '[' 0 -ne 0 ']'
+ return 0
+ fxnListDirContents /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ fxnPP 'Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
+ printf '==== %-66s ====\n' 'Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge'
==== Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ====
+ ls -l /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ sed -e 's/^/      /g'
      total 48
      -rw-r--r-- 1 sri sri  656 Jan 21 10:29 Dockerfile.config
      -rw-r--r-- 1 sri sri 1904 Jan 21 10:29 Dockerfile.template
      -rw-r--r-- 1 sri sri 3453 Jan 21 10:29 duebuild-readme.md
      drwxr-xr-x 4 sri sri 4096 Jan 21 10:29 filesystem
      -rw-r--r-- 1 sri sri 5267 Jan 21 10:29 install-config-common-lib.template
      -rwxr-xr-x 1 sri sri 7882 Jan 21 10:29 post-install-config.sh.template
      -rwxr-xr-x 1 sri sri 2479 Jan 21 10:29 pre-install-config.sh.template
      -rw-r--r-- 1 sri sri 8722 Jan 21 10:29 README.md
+ USE_TEMPLATE_PATH=/home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge
+ fxnHeader 'Creating directory to be used for container build at: [ onie-build-debian-9 ]'
+ echo ''

+ echo ' __________________________________________________________________________ '
 __________________________________________________________________________ 
+ echo '|'
|
+ echo '| Creating directory to be used for container build at: [ onie-build-debian-9 ]'
| Creating directory to be used for container build at: [ onie-build-debian-9 ]
+ echo '|__________________________________________________________________________ '
|__________________________________________________________________________ 
+ echo ''

+ fxnPP 'Copying non-template files from [ /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ] to [ onie-build-debian-9 ]'
+ printf '==== %-66s ====\n' 'Copying non-template files from [ /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ] to [ onie-build-debian-9 ]'
==== Copying non-template files from [ /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge ] to [ onie-build-debian-9 ] ====
+ '[' '!' -e /usr/bin/rsync ']'
+ fxnEC rsync --archive --verbose '--exclude=*.template' /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge/ /home/sri/src/DUE/due-build-merge/onie-build-debian-9
+ rsync --archive --verbose '--exclude=*.template' /home/sri/src/DUE/due-build-merge/onie-build-debian-9-template-merge/ /home/sri/src/DUE/due-build-merge/onie-build-debian-9
sending incremental file list
created directory /home/sri/src/DUE/due-build-merge/onie-build-debian-9
./
Dockerfile.config
README.md
duebuild-readme.md
filesystem/
filesystem/etc/
filesystem/etc/apt/
filesystem/etc/apt/sources.list.d/
filesystem/etc/apt/sources.list.d/stretch-backports.list
filesystem/usr/
filesystem/usr/local/
filesystem/usr/local/bin/
filesystem/usr/local/bin/container-create-user.sh
filesystem/usr/local/bin/duebuild

sent 42,197 bytes  received 245 bytes  84,884.00 bytes/sec
total size is 41,476  speedup is 0.98
+ status=0
+ '[' 0 -ne 0 ']'
+ return 0
+ fxnListDirContents /home/sri/src/DUE/due-build-merge/onie-build-debian-9
+ fxnPP 'Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9'
+ printf '==== %-66s ====\n' 'Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9'
==== Contents of: /home/sri/src/DUE/due-build-merge/onie-build-debian-9 ====
+ ls -l /home/sri/src/DUE/due-build-merge/onie-build-debian-9
+ sed -e 's/^/      /g'
      total 24
      -rw-r--r-- 1 sri sri  656 Jan 21 10:29 Dockerfile.config
      -rw-r--r-- 1 sri sri 3453 Jan 21 10:29 duebuild-readme.md
      drwxr-xr-x 4 sri sri 4096 Jan 21 10:29 filesystem
      -rw-r--r-- 1 sri sri 8722 Jan 21 10:29 README.md
++ uname -m
+ HOST_ARCH=i686
+ case $HOST_ARCH in
+ fxnERR 'Cannot map [ i686 ] to a Docker contianer type. Exiting.'
+ echo ''

+ printf 'ERROR at libdue line 1331 :  %s\n' 'Cannot map [ i686 ] to a Docker contianer type. Exiting.'
ERROR at libdue line 1331 :  Cannot map [ i686 ] to a Docker contianer type. Exiting.
+ echo ''

+ exit 1

**Comment by ehdoyle** [comment]
Hi - sorry about the lag in getting back to you on this.
I'd agree with your assesment about it being related to the VM setup - the host architecture is coming back as i686, and DUE is expecting a x86_64 when checking to see if the desired architcture is different from the host's, in whcih case it will try to emuluate it and the i686 != x86_64 is tripping it up 
[here](https://github.com/CumulusNetworks/DUE/blob/d16fba5cab1215e9f46ff6a278ea5c99bdcac99a/libdue#L569)
It looks like the i686 is a 32 bit architecture, so that should map to i386 in Debian's naming conventions, I think. 
Getting a i386 container as follows _might_ work:
./due --create --from i386/debian:9 --description "ONIE Build Debian 9" --name onie-build-debian-9 --prompt ONIE-9 --tag onie --use-template onie
Do you have any details on how the VM was set up so that I could try to replicate it?
Thanks!

**Comment by sramkrishna** [comment]
Oh that's ok! I figured it out already and have a new debian 9 VM that works nicely and that is truly 64 bit. Apparently GNOME Boxes downloaded the wrong Debian 10 VM image - it was i386 instead of amd64.
