### ISSUE TITLE
cannot build ONIE in any released enviroment (all machines fail)

### ISSUE THREAD

**Issue by sxsic** [CumulusNetworks/DUE#34]
been fighting with building onie for 7 days now, i've followed the tutorial videos very closely and believe this to be an issue with either DUE or ONIE src code itself. the error im getting is "Make[2] *** no rule to make target '/home/awalls/src/onie/encryption/machines/kvm_x86_64/keys/ONIE/efi-keys/ONIE-shim-key-cert.pem' --- 

I want to know exactly what you are running DUE in. im using the latest everything i've been following your notes very closely. nothing seems to get around signing.keys.x509.  
Please help!

**Comment by ehdoyle** [comment]
Hi - I've split my suggestions based on areas of troubleshooting
DUE
Due builds have been running on either Debian 10 or Ubuntu 20.04 systems, with a build of the Debian 10 container:
**./due --create --from debian:10 --description "ONIE Build Debian 10" --name onie-build-debian-10 --prompt ONIE-10 --tag onie --use-template onie**
Do run it as  **due --run --dockerarg --privileged**   <- that allows it to loopback mount the virtual usb drive and put the keys there, and may get around some errors.
Docker versions have been both from Debian ( docker.io ) and Docker - (docker-ce ).

ONIE
You mentioned the tutorial videos, so you've probably seen this one:
[https://www.youtube.com/watch?v=evzkiiRRIvw&t=575s](https://www.youtube.com/watch?v=evzkiiRRIvw&t=575s)
The KVM target builds with secure boot active by default (as it's intended to be a demonstration of the latest ONIE features), so there are a few more steps.
Once you log in to the ONIE contaner, cd to ONIE's build-config directory, 
Make sure you are on the master branch in a Debian 10 container building kvm_x86_64.  Currently the qemu_armv8a target is the only other one that builds on master, as machine vendors have yet to upgrade to it.
then run:
**make MACHINE=kvm_x86_64 signing-keys-install**    <- should put keys under onie/encryption
**make MACHINE=kvm_x86_64 -j4 shim self sign**       <- create the shim signed with the keys just created
**make MACHINE=kvm_x86_64 -j4 all  demo**                       <- build ONIE and demo os

I'd suggest starting from a clean checkout, as partial build cases haven't been thoroughly debugged. If you can follow the full tutorial above ( the link has an offset to the part where keys are discussed) it should get you a working kvm_x86_64, and if not, we will have the exact spot where things stopped working for you and will be able to debug from there.
Hope that helps.

**Comment by ehdoyle** [comment]
Hi - just following up to see if the build off the master branch fixed it? Thanks.

**Comment by sxsic** [comment]
sorry I hadn't replied, I tried using 08.2021 and that one worked right away :)

**Comment by ehdoyle** [comment]
Excellent. I'll close this out. Thanks!
