### ISSUE TITLE
nproc

### ISSUE THREAD

**Issue by stappersg** [CumulusNetworks/DUE#8]
Seeing
```
run dpkg-buildpackage -us -uc with 4 jobs (unless a different -jX has been passed)
```
made me creating this  issue   :-)

I don't know where the 4 comes from, so I felt the need to tell about `nproc`.

Tool `nproc` is default available and returns the number of processors a system has.
Typical use case is
```
make -j $(nproc)
```

So I'm suggestion
> run dpkg-buildpackage -us -uc with _nproc_ jobs (unless a different -jX has been passed)

And do feel free to close this issue.

**Comment by ehdoyle** [comment]
That looks good to me. The only time I've seen too much computing power be a problem is in code that has race conditions on build, and if that's the case, the user can limit it with --jobs 1.
